// src/routes/Wormhole.svelte
<script lang="ts">
  import { EllipseCurve, Group, Line, Vector2, Vector3 } from "three";
  import { T, useTask, type Props } from "@threlte/core";
  type LineProps = Props<typeof Line>;

  let { loaded = $bindable(false) } = $props();
  let group = $state<Group>();

  useTask((delta) => {
    if (!group) return;
    group.rotation.z += 0.1 * delta;
    group.rotation.y = 0.4;
  });

  const N = 40;
  const z_ = Array(N + 1)
    .fill(0)
    .map((_, i) => ((i / N) * 2 - 1) * 2);
  const r_ = (z: number) => Math.pow(z, 4) + 0.05;
</script>

<T.PerspectiveCamera
  makeDefault
  position={[0, -2, 2]}
  oncreate={(ref) => {
    ref.lookAt(new Vector3(0, 0, 0));
    loaded = true;
  }}
></T.PerspectiveCamera>

{#snippet LineF(points: Vector2[] | Vector3[], p: LineProps)}
  <T.Line
    {...p}
    oncreate={(ref) => {
      ref.geometry.setFromPoints(points);
    }}
  >
    <T.BufferGeometry></T.BufferGeometry>
    <T.LineBasicMaterial opacity={0.5} transparent></T.LineBasicMaterial>
  </T.Line>
{/snippet}

{#snippet Circle(radius: number, p: LineProps)}
  {@render LineF(new EllipseCurve(0, 0, radius, radius).getPoints(100), p)}
{/snippet}

<T.Group bind:ref={group} scale={0.5}>
  {#each z_ as z, i}
    {@render Circle(r_(z), { position: [0, 0, z] })}
    {@render LineF(
      z_.map((z) => new Vector3(r_(z), 0, z)),
      { rotation: [0, 0, (i / N) * 2 * Math.PI] },
    )}
  {/each}
</T.Group>

// src/components/wormhole.tsx
"use client";

import { Fragment, useLayoutEffect, useRef } from "react";
import { Canvas, useFrame } from "react-three-fiber";
import { EllipseCurve, Group, Line, Vector2, Vector3 } from "three";
import { getColor } from "./color-state";

export function WormHole() {
  return (
    <div
      className="absolute top-0 -z-10 w-full h-full transition-opacity fade"
      style={{
        maskImage:
          "linear-gradient(to bottom, rgba(0,0,0,0), white, rgba(0,0,0,0))",
      }}
    >
      <Canvas camera={{ rotation: [0, 0, 0.4] }}>
        <WormHoleObject></WormHoleObject>
      </Canvas>
    </div>
  );
}

function WormHoleObject() {
  const group = useRef<Group>(null);
  useFrame(({ clock }) => {
    if (!group.current) return;
    group.current.rotation.z = 0.1 * clock.elapsedTime;
    group.current.rotation.x = -0.001 * window.scrollY - 0.8;
  });

  const N = 40;
  const z_ = Array(N + 1)
    .fill(0)
    .map((_, i) => ((i / N) * 2 - 1) * 2);
  const r_ = (z: number) => Math.pow(z, 4) + 0.05;

  return (
    <group ref={group} scale={2}>
      {z_.map((z, i) => {
        const r = r_(z);
        const points = z_.map((z) => new Vector3(r_(z), 0, z));
        return (
          <Fragment key={i}>
            <Circle radius={r} position={[0, 0, z]}></Circle>
            <LineF
              points={points}
              rotation={[0, 0, (i / N) * 2 * Math.PI]}
            ></LineF>
          </Fragment>
        );
      })}
    </group>
  );
}

type Circle = {
  radius?: number;
  position?: number[];
  rotation?: number[];
};
function Circle({ radius, ...props }: Circle) {
  const curve = new EllipseCurve(0, 0, radius, radius);
  return <LineF points={curve.getPoints(100)} {...props}></LineF>;
}

type LineF = {
  points: Vector3[] | Vector2[];
  position?: number[];
  rotation?: number[];
};
function LineF({ points, ...props }: LineF) {
  const line = useRef<Line>(null);
  useLayoutEffect(() => {
    if (!line.current) return;
    line.current.geometry.setFromPoints(points);
  }, []);

  const color = getColor();

  return (
    // @ts-ignore
    <line ref={line} {...props}>
      <bufferGeometry></bufferGeometry>
      <lineBasicMaterial
        color={color}
        opacity={0.5}
        transparent
      ></lineBasicMaterial>
    </line>
  );
}
